name: Angular Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: drop-duchy-calculator/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: drop-duchy-calculator

      - name: Build Angular application (production)
        run: npm run build -- --configuration production
        working-directory: drop-duchy-calculator

      - name: Upload dist to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: drop-duchy-calculator/dist/drop-duchy-calculator/browser